name: arkmuntasser
description: Just a super cool cat doin' some code stuff
url: https://arkmuntasser.github.io/

# Includes an icon in the footer for each username you enter
footer-links:
  - name: email
    icon: mail-alt
    url: mailto:arkmuntasser@gmail.com
  - name: github
    icon: github-circled
    url: https://github.com/arkmuntasser
  - name: twitter
    icon: twitter
    url: https://twitter.com/arkmuntasser

# Portfolio collection
portfolio:
  - name: roosterteeth
    label: Rooster Teeth
    url: http://roosterteeth.com
    image: ''
    related-post:
    business-tags: freelance
    dev-tags:
      - tag: backend
      - tag: php
      - tag: laravel
    featured: true
  - name: shopsws
    label: Shop SWS
    url: http://shopsws.com
    image: ''
    related-post:
    business-tags: sws computers
    dev-tags:
      - tag: php
      - tag: backend
      - tag: frontend
      - tag: magento
      - tag: estore
    featured: true
  - name: northeastcr
    label: Northeast Computer Repair
    url: http://northeastcr.com
    image: ''
    related-post:
    business-tags: freelance
    dev-tags:
      - tag: php
      - tag: backend
      - tag: frontend
      - tag: wordpress
    featured: true
  - name: northeastcr
    label: Northeast Computer Repair
    url: http://northeastcr.com
    image: ''
    related-post:
    business-tags: freelance
    dev-tags:
      - tag: php
      - tag: backend
      - tag: frontend
      - tag: wordpress
    featured: true

permalink: pretty

permalink: /blog/:slug/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
