name: arkmuntasser
description: Just a super cool cat doin' some code stuff...
url: https://arkmuntasser.github.io/

# Includes an icon in the footer for each username you enter
footer-links:
  - name: twitter
    icon: twitter
    url: https://twitter.com/arkmuntasser
  - name: github
    icon: github-circled
    url: https://github.com/arkmuntasser
  - name: email
    icon: mail-alt
    url: mailto:arkmuntasser@gmail.com

# Projects
projects:
  - name: happy-new-year
    giturl: https://github.com/arkmuntasser/happy-new-year
    puburl: https://arkmuntasser.github.io/happy-new-year
    image: ''
    description: 🎉 Happy New Year! - A simple countdown to the new year with fireworks! 🎉
  - name: ui-components
    giturl: https://github.com/arkmuntasser/ui-components
    puburl:
    image: ''
    description: A collection/playground of UI components and experiments.
  - name: css-triggers
    giturl: https://github.com/arkmuntasser/css-triggers
    puburl:
    image: ''
    description: An Atom package that lets you know if your css will trigger layout, paint and/or composite.
  - name: before-after
    giturl: https://github.com/arkmuntasser/before-after
    puburl: http://arkmuntasser.github.io/before-after
    image: ''
    description: A progressively enhanced before and after image widget.
  - name: meme
    giturl: https://github.com/arkmuntasser/meme
    puburl: http://arkmuntasser.github.io/meme
    image: ''
    description: A web app for making elegant shareable content using images, text, color, and branding.

# Portfolio collection
portfolio:
  - name: columbus
    label: Experience Columbus
    url: http://experiencecolumbus.com
    image: ''
    description: Come experience Columbus, Ohio and see what makes us a great city to visit. Find things to do, hotels, restaurants, events and visitor travel information.
    related-post:
    business-tags: simpleview
    dev-tags:
      - tag: frontend
    featured: true
  - name: roosterteeth
    label: Rooster Teeth
    url: http://roosterteeth.com
    image: ''
    description: Rooster Teeth is a production studio based in Austin, TX responsible for some of the most watched and celebrated online series ever.
    related-post:
    business-tags: freelance
    dev-tags:
      - tag: backend
      - tag: php
      - tag: laravel
    featured: true
  - name: shopsws
    label: Shop SWS
    url: http://shopsws.com
    image: ''
    description: SWS is dedicated to providing the highest quality computer sales and service to southern Arizona's business and private communities.
    related-post:
    business-tags: sws computers
    dev-tags:
      - tag: php
      - tag: backend
      - tag: frontend
      - tag: magento
      - tag: estore
    featured: true
  - name: northeastcr
    label: Northeast Computer Repair
    url: http://northeastcr.com
    image: ''
    description: At Northeast Computer Repair we take a different approach to your digital needs. Our principles are honesty, integrity, expertise, and promptness.
    related-post:
    business-tags: freelance
    dev-tags:
      - tag: php
      - tag: backend
      - tag: frontend
      - tag: wordpress
    featured: true

permalink: pretty

permalink: /blog/:slug/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
