name:          SV Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML, CSS and JavaScript.
url:           https://arkmuntasser.github.io/

markdown:      rdiscount
permalink:     pretty
